apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}-local
  labels:
    app: ${project.artifactId}-local
spec:
  selector:
    app: ${project.artifactId}-local
  type: NodePort
  ports:
    - name: wiremock-http
      port: 8090
      nodePort: 30090
    - name: wiremock-https
      port: 8443
      nodePort: 30093
    - name: db
      port: 5432
      nodePort: 30005
