# This example was copied from https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
# altered to reference sdem schemas
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://localhost:8080
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "../sdem/pets-v1.json"
        '500':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../sdem/error-v1.json"
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        '500':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../sdem/error-v1.json"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "../sdem/pet-v1.json"
        '404':
          description: not found error
          content:
            application/json:
              schema:
                $ref: "../sdem/error-v1.json"
        '500':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../sdem/error-v1.json"
