{
  enabled: true
  name: "Latency"
  description: null
  nrql: {
    query: "SELECT sum(http_server_requests_seconds_sum) FROM Metric WHERE `label.app.kubernetes.io/name` = 'do-bitbucket-scm-event-api' AND namespaceName = '{{cookiecutter.prefix}}-test' FACET uri, method"
  }
  expiration: null
  runbookUrl: null
  signal: {
    aggregationDelay: 120
    aggregationMethod: EVENT_FLOW
    aggregationTimer: null
    fillValue: null
    aggregationWindow: 60
    fillOption: NONE
    slideBy: null
  }
  terms: [
      {
        operator: ABOVE
        threshold: 1
        priority: CRITICAL
        thresholdDuration: 180
        thresholdOccurrences: ALL
      }
      {
        operator: ABOVE
        threshold: 1
        priority: WARNING
        thresholdDuration: 120
        thresholdOccurrences: ALL
      }
  ]
  violationTimeLimitSeconds: 259200
}
