{
  enabled: true
  name: "Traffic"
  description: null
  nrql: {
    query: "SELECT sum(http_server_requests_seconds_count) FROM Metric WHERE `label.app.kubernetes.io/name` = '{{cookiecutter.artifact_id}}' AND namespaceName = '{{cookiecutter.prefix}}-test' FACET uri, method"
  }
  expiration: null
  runbookUrl: null
  signal: {
    aggregationDelay: 120
    aggregationMethod: EVENT_FLOW
    aggregationTimer: null
    fillValue: null
    aggregationWindow: 60
    fillOption: NONE
    slideBy: null
  }
  terms: [
    {
      operator: ABOVE
      threshold: 20
      priority: CRITICAL
      thresholdDuration: 120
      thresholdOccurrences: ALL
    }
    {
      operator: ABOVE
      threshold: 20
      priority: WARNING
      thresholdDuration: 60
      thresholdOccurrences: ALL
    }
  ]
  violationTimeLimitSeconds: 259200
}
