apiVersion: twg.co.nz/v1alpha1
kind: newrelicAlert
metadata:
  policies:
    - name: "INFO | DEV | {{cookiecutter.artifact_id}} | {{cookiecutter.prefix|upper}}"
      incidentPreference: PER_POLICY
      conditions:
        - name: "P5 | Kubernetes | {{cookiecutter.artifact_id}} | Check Error Request Count >10 for 1m"
          definition: error-rate-condition.gql
          tags:
            - key: service
              value: {{cookiecutter.artifact_id}}
            - key: environment
              value: dev
            - key: criticality
              value: medium
        - name: "P5 | Kubernetes | {{cookiecutter.artifact_id}} | Check Request Count >20 for 2m"
          definition: traffic-condition.gql
          tags:
            - key: service
              value: {{cookiecutter.artifact_id}}
            - key: environment
              value: dev
            - key: criticality
              value: medium
        - name: "P5 | Kubernetes | {{cookiecutter.artifact_id}} | Check Request Latency >1s for 2m"
          definition: latency-condition.gql
          tags:
            - key: service
              value: {{cookiecutter.artifact_id}}
            - key: environment
              value: dev
            - key: criticality
              value: medium
        - name: "P5 | Kubernetes | {{cookiecutter.artifact_id}} | Check CPU Utilization >70% for 2m"
          definition: high-cpu-utilization-condition.gql
          tags:
            - key: service
              value: {{cookiecutter.artifact_id}}
            - key: environment
              value: dev
            - key: criticality
              value: medium
        - name: "P5 | Kubernetes | {{cookiecutter.artifact_id}} | Check Memory Usage >70% for 1m"
          definition: high-memory-usage-condition.gql
          tags:
            - key: service
              value: {{cookiecutter.artifact_id}}
            - key: environment
              value: dev
            - key: criticality
              value: medium
