logging:
  config: classpath:log4j2-local.xml

# Include the features endpoint
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,verifier,features

# launchdarkly configs
### file type data-source for testing or local development
launchdarkly:
  data-source:
    type: FILE
    file:
      location: ${java.io.tmpdir}/featuretoggles/local-features.json
      auto-reload: true

# OpenFeign client config
pets:
  name: pets-remote
  url: http://localhost:30090
