logging:
  config: classpath:log4j2-local.xml

twg:
  sdem:
    encryption:
      service-api-config:
        # URLs must not have trailing /
        base-url: "http://localhost:30090/vault-proxy"
        auth:
          token-url: "http://localhost:30090/auth/oauth2/token"

# Include the features endpoint
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,verifier,features

# launchdarkly configs
### file type data-source for testing or local development
launchdarkly:
  data-source:
    type: FILE
    file:
      location: ${java.io.tmpdir}/featuretoggles/local-features.json
      auto-reload: true

# OpenFeign client config
animals:
  name: animals
  url: http://localhost:30090
